# Generated by Django 4.2.6 on 2023-10-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=255)),
                ('startup_frames', models.CharField(max_length=255)),
                ('active_frames', models.CharField(max_length=255)),
                ('recovery_frames', models.CharField(max_length=50)),
                ('on_hit', models.CharField(max_length=255)),
                ('on_block', models.CharField(max_length=255)),
                ('cancel', models.CharField(max_length=255)),
                ('damage', models.CharField(max_length=255)),
                ('scaling', models.CharField(max_length=255)),
                ('drive_increase', models.CharField(max_length=255)),
                ('drive_decrease', models.CharField(max_length=255)),
                ('drive_decrease_pc', models.CharField(max_length=255)),
                ('sa_increase', models.CharField(max_length=255)),
                ('high_low', models.CharField(max_length=255)),
                ('misc', models.TextField()),
                ('character', models.CharField(max_length=50)),
            ],
        ),
    ]
