# Generated by Django 4.2.6 on 2023-10-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
        migrations.AlterField(
            model_name='move',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framedata.character'),
        ),
    ]
